create database food_delivery;
use food_delivery;
create table products(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    price DECIMAL(15, 2) NOT NULL,
    sale_price DECIMAL(15, 2),
    quantity INT NOT NULL,
    image TEXT NOT NULL,
    category VARCHAR(255) DEFAULT NULL,
    food_type VARCHAR(255) DEFAULT NULL
);

INSERT INTO products(name, description, price, sale_price, quantity, image, category, food_type) 
	VALUES ("Veg Loaded Pizza", "Pizza is a dish of Italian origin, made with an oven-baked, flat, generally round bread that is often covered with tomatoes or a tomato-based sauce and mozzarella cheese. Other toppings are added according to region, culture, or personal preference. Originating as a part of Italian cuisine, the dish has become popular in many different parts of the world, particularly the United States, where numerous varieties have been developed, pizza restaurant chains have flourished, and pizza has become a home delivery item as well as being available as a frozen food ready to bake at home.", 19.99, 17.99, 10, "f1.png", "Pizza", "Italian"),
		   ("Salmon Burger", "A hamburger, or simply burger, is a food consisting of fillings—usually a patty of ground meat, typically beef—placed inside a sliced bun or bread roll. Hamburgers are often served with cheese, lettuce, tomato, onion, pickles, bacon, or chilis; condiments such as ketchup, mustard, mayonnaise, relish, or a 'special sauce', often a variation of Thousand Island dressing; and are frequently placed on sesame seed buns. A hamburger patty topped with cheese is called a cheeseburger.", 12.99, 10.99, 10, "f2.png", "Burger", "Western"),
           ("Veg Loaded Pizza", "Pizza is a dish of Italian origin, made with an oven-baked, flat, generally round bread that is often covered with tomatoes or a tomato-based sauce and mozzarella cheese. Other toppings are added according to region, culture, or personal preference. Originating as a part of Italian cuisine, the dish has become popular in many different parts of the world, particularly the United States, where numerous varieties have been developed, pizza restaurant chains have flourished, and pizza has become a home delivery item as well as being available as a frozen food ready to bake at home.", 23.99, NULL, 10, "f3.png", "Pizza", "Italian"),
           ("White Pasta", "Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking. Rice flour, or legumes such as beans or lentils, are sometimes used in place of wheat flour to yield a different taste and texture, or as a gluten-free alternative. Pasta is a staple food of Italian cuisine.", 5.99, NULL, 10, "f4.png", "Extras", "Western"),
           ("French Fries", "French fries are served hot, either soft or crispy, and are generally eaten as part of lunch or dinner or by themselves as a snack, and they commonly appear on the menus of diners, fast food restaurants, pubs, and bars. They are often salted and may be served with ketchup, vinegar, mayonnaise, tomato sauce, or other local specialities. Fries can be topped more heavily, as in the dishes of poutine or chili cheese fries. French fries can be made from sweet potatoes instead of potatoes. A baked variant, oven fries, uses less or no oil.", 2.99, NULL, 10, "f5.png", "Extras", "French"),
           ("Chicken Supreme Pizza", "Pizza is a dish of Italian origin, made with an oven-baked, flat, generally round bread that is often covered with tomatoes or a tomato-based sauce and mozzarella cheese. Other toppings are added according to region, culture, or personal preference. Originating as a part of Italian cuisine, the dish has become popular in many different parts of the world, particularly the United States, where numerous varieties have been developed, pizza restaurant chains have flourished, and pizza has become a home delivery item as well as being available as a frozen food ready to bake at home.", 25.99, 21.99, 10, "f6.png", "Pizza", "Italian"),
           ("Turkey burger", "A hamburger, or simply burger, is a food consisting of fillings—usually a patty of ground meat, typically beef—placed inside a sliced bun or bread roll. Hamburgers are often served with cheese, lettuce, tomato, onion, pickles, bacon, or chilis; condiments such as ketchup, mustard, mayonnaise, relish, or a 'special sauce', often a variation of Thousand Island dressing; and are frequently placed on sesame seed buns. A hamburger patty topped with cheese is called a cheeseburger.", 15.99, NULL, 10, "f7.png", "Burger", "Western"),
           ("Veggie burger", "A hamburger, or simply burger, is a food consisting of fillings—usually a patty of ground meat, typically beef—placed inside a sliced bun or bread roll. Hamburgers are often served with cheese, lettuce, tomato, onion, pickles, bacon, or chilis; condiments such as ketchup, mustard, mayonnaise, relish, or a 'special sauce', often a variation of Thousand Island dressing; and are frequently placed on sesame seed buns. A hamburger patty topped with cheese is called a cheeseburger.", 16.99, NULL, 10, "f8.png", "Burger", "Western"),
           ("Red Pasta", "Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking. Rice flour, or legumes such as beans or lentils, are sometimes used in place of wheat flour to yield a different taste and texture, or as a gluten-free alternative. Pasta is a staple food of Italian cuisine.", 7.99, NULL, 10, "f9.png", "Extras", "Western");
